### ISSUE TITLE
Missing icon: cs-sources

### ISSUE THREAD

**Issue by harmin-parra** [mjkim0727/Eleven-icon-theme#15]
I can suggest something like this:

![cs-sources](https://github.com/mjkim0727/Eleven-icon-theme/assets/16239820/555de65d-d4f3-4dfb-b81d-37915afc1051)

**Comment by mjkim0727** [comment]
https://github.com/mjkim0727/Eleven-icon-theme/commit/6eb1881036bfa0a7e799ad727f512abee101c092

I did it.
