### ISSUE TITLE
Klipper-symbolic in Eleven-Dark

### ISSUE THREAD

**Issue by Dejweed** [mjkim0727/Eleven-icon-theme#3]
Hello!

The Klipper icon in the KDE system tray doesn't follow the current color scheme when using Eleven-Dark, and is much bigger than other icons. This can be seen when using 2x or 3x scale.

![image](https://github.com/mjkim0727/Eleven-icon-theme/assets/65261588/3891860a-3973-4d23-965a-e8e5f8886556)

The issue is probably the Eleven-Dark/symbolic/`klipper-symbolic.svg`. Removing it fixes my issue.

**Comment by mjkim0727** [comment]
Removed it.
